[package]
name = "excel-emulator2"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
petgraph = "0.6.2"
regex = "1.6.0"
thiserror = "1.0.31"

[build-dependencies]
lalrpop = "0.19.8"
